name: Build
 
on:
  push:
    branches: [ master ]
  pull_request:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
 
      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
 
      - run: chmod +x gradlew
 
      - run: ./gradlew :showcaseoverlay:assembleRelease :app:assembleDebug